/**:
  ros__parameters:
    debug: true                     # 关闭调试图像，节省资源
    target_frame: odom
    detect_color: 0
    binary_thres: 90
    use_pca: true
    use_ba: false                    # 后相机关闭 BA 优化，提高速度
    light.min_ratio: 0.0001
    light.max_ratio: 1.0
    light.max_angle: 40.0
    light.color_diff_thresh: 20
    armor.min_light_ratio: 0.8
    armor.min_small_center_distance: 0.8
    armor.max_small_center_distance: 3.5
    armor.min_large_center_distance: 3.5
    armor.max_large_center_distance: 8.0
    armor.max_angle: 35.0
    classifier_threshold: 0.6         # 降低阈值，避免漏检远处小目标
    ignore_classes: ["negative"]